# This file is used by Copier to track the template version
# and enable template updates in generated projects

_commit: d9fd410e814283efeeb0deeb99b240c51415cf77
_src_path: gh:stateful-y/python-package-copier
author_email: gtauzin@stateful-y.io
author_name: Guillaume Tauzin
description: Kedro-Dagster makes it easy to deploy Kedro projects to Dagster
github_username: stateful-y
include_actions: true
include_examples: false
license: Apache-2.0
max_python_version: '3.13'
min_python_version: '3.10'
package_name: kedro_dagster
project_name: Kedro-Dagster
project_slug: kedro-dagster
