site_name: Kedro-Dagster's documentation
site_url: https://kedro-dagster.readthedocs.io/en/latest/
repo_name: stateful-y/kedro-dagster
repo_url: https://github.com/stateful-y/kedro-dagster

edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Introduction: pages/intro.md
  - Getting started: pages/getting-started.md
  - Example: pages/example.md
  - User guide: pages/guide.md
  - Reference: pages/reference.md
  - FAQ: pages/faq.md

theme:
  name: material
  custom_dir: docs/material/overrides

  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight

  favicon: images/favicon.png
  logo: assets/logo.png

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ["."]  # for root of repo

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 4
            show_root_heading: false
            show_root_toc_entry: false
            show_source: true
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: list
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false
              returns_named_value: false
          paths: [src]

copyright: Copyright &copy; 2024 - 2025 Guillaume Tauzin
